### ISSUE TITLE
Testing build docker-compose

### ISSUE THREAD

**Issue by okisidentarisu** [jphacks/D_2203#8]
## add a feedbag later

**Comment by okisidentarisu** [comment]
@lion-rion
The "docker-compose" command worked on **V1** and gave me an error.
Therefore, I used the "docker compose" command, which supports **V2**.

Sorry for the screenshot.
<img width="977" alt="docker_compose_version" src="https://user-images.githubusercontent.com/105708117/196023125-03fcaa2b-d055-46f0-a8f8-239de79d6ed8.png">

**Comment by okisidentarisu** [comment]
As for the build, the "docker compose" command seems to work.

**Comment by okisidentarisu** [comment]
And the page have worked correctly.

**Comment by lion-rion** [comment]
I see, I use docker desktop on Macbook (arm64).
There are obviously some defference. 
The version problem will be solved someday. Sorry about that.

**Comment by okisidentarisu** [comment]
Thanks for the quick reply!
This Issue completes what needs to be checked, so if versioning issues become more pronounced, please raise another Issue.
